import { getAreaResult } from "./locator.js";

getAreaResult(
  "4684276156830303372",
  [0, 0],
  [
    // "buriedTreasure",
    // "dungeon",
    // "netherFortress",
    // "bastionRemnant",
    // "endCity",
    // "slimeChunk",
    "stronghold",
    "village",
    // "mineshaft",
    // "woodlandMansion",
    // "pillagerOutpost",
    // "oceanRuin",
    // "oceanMonument",
    // "shipwreck",
    // "desertTemple",
    // "jungleTemple",
    "witchHut",
    "igloo",
    // "ruinedPortalOverworld",
    // "ruinedPortalNether",
    // "spawn",
    // "fossil",
    // "ravine",
    // "endGateway",
    // "amethystGeode",
    // "ancientCity",
    // "itemOverworld",
    // "oreVein",
    // "cave",
    // "desertWell",
    // "trailRuin",
  ],
).then(console.log);
